FROM ubi8

# We don't need the deps that rhosp-director-images-ipa pulls in
# use rpm to install without them to keep the image size down as
# much as possible
RUN dnf download rhosp-director-images-ipa-$(uname -m) --destdir /tmp/packages && \
    rpm -i --nodeps /tmp/packages/rhosp-director-images-ipa-* && \
    echo $(rpm -q --queryformat '%{VERSION}-%{RELEASE}' /tmp/packages/rhosp-director-images-ipa-$(uname -m)-*.rpm) > /usr/share/rhosp-director-images/version-latest.txt && \
    mv /usr/share/rhosp-director-images/ironic-python-agent-*.$(uname -m).tar /usr/share/rhosp-director-images/ironic-python-agent-latest.tar && \
    rm -rf /tmp/packages && \
    dnf clean all

COPY ./get-resource.sh /usr/local/bin/get-resource.sh
